# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
    - git config --global user.name "Test"
    - git config --global user.email "test@test.com"

install:
  - pip install -r requirements.txt

script:
  - bash tests/test_install.sh
