# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install cookiecutter sphinx mock

script:
  - bash tests/test_install.sh
