# https://ci.appveyor.com/project/jakubroztocil/httpie
build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
init:
  - "git config --global user.email 'foo@example.com'"
  - "git config --global user.name 'foo'"
install:
  - ps: (new-object net.webclient).DownloadFile("https://raw.github.com/pypa/pip/master/contrib/get-pip.py", "C:/get-pip.py")
  - "%PYTHON%/python.exe C:/get-pip.py"
  # Note: Cannot use quotes when setting variables
  - set PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%
  - "ECHO %PATH%"
  - ps: If ($Env:PYTHON -like "*27") {
        $Env:REQUIREMENT_FILE="python27.txt"
      }
      Else
      {
        $Env:REQUIREMENT_FILE="python3.txt"
      }
  - "pip install -r %REQUIREMENT_FILE%"
test_script:
  - "python tests/test.py"
